"""
tm6_make_woven_fracture_deck.py — woven damage-tolerance FAILURE sim (phase-field crack deflection).

The non-fused woven retention study (tm6_make_woven_cell_deck.py) proved that non-fused crossings give
NO *linear-stiffness* redundancy, so any benefit of weak crossings must be a FRACTURE-regime effect.
This deck tests that directly: it drives a crack through a notched plate and compares two idealizations of the same
architecture —

  fused    : uniform fracture toughness Gc everywhere  -> crack runs STRAIGHT through (brittle).
  nonfused : weak horizontal INTERFACES (the delaminating / sliding woven crossings) at a set pitch,
             where Gc drops to Gc_low  -> the crack DEFLECTS/delaminates onto the weak planes.

Crack deflection at weak interfaces (Cook–Gordon / He–Hutchinson) is the toughening principle proposed
for nacre, Bouligand, and non-fused woven lattices: the interface turns the crack, lengthening its path
and dissipating more energy per unit advance. The metric is the WORK OF FRACTURE = area under the
reaction–displacement curve (postprocessors reaction_x, applied_disp). RESULT (results/woven_cell/):
in this idealization the weak interfaces do NOT toughen; at equal initial stiffness the nonfused plate
reaches 0.32x the fused peak load and 0.10x its total work (docs/FRACTURE.md).

Model: 2D PLANE_STRAIN unit square, edge notch (vertical, seeded SMOOTH along x=0.5, y<0.4). Mode-I
opening by horizontal tension (pull right edge +x, fix left x; y pinned on both to suppress RBM). Brittle
phase-field fracture (AT2), VI bounded solver for irreversibility, IterationAdaptiveDT through snap-through.
Material scale kept at the VALIDATED tm6_stageD.i values (C_ijkl ~127, gc 1e-3, l 0.04) so the solve is
well-conditioned; the fused/nonfused comparison is scale-independent.

INPUTS   <fused|nonfused> <out.i> [n_interfaces=3] [gc_high=1e-3] [gc_ratio=0.1]
         (gc_low = gc_high*gc_ratio at the weak interfaces)
OUTPUTS  the MOOSE deck at <out.i> + a one-line summary on stdout. Compare two runs with
         tm6_fracture_compare.py; the banked comparison is in results/woven_cell/RESULTS.md.
Usage: python -m abcad.fracture.tm6_make_woven_fracture_deck <fused|nonfused> <out.i> \
       [n_interfaces=3] [gc_high=1e-3] [gc_ratio=0.1]
"""

from __future__ import annotations

import sys


def main(argv=None):
    """CLI entry point: write the fused or non-fused woven fracture deck."""
    argv = sys.argv[1:] if argv is None else list(argv)
    # Positional CLI: print the usage (this module's docstring) for -h/--help or missing arguments
    # rather than failing with an IndexError/ValueError traceback.
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0 if argv else 2
    mode = argv[0]  # 'fused' or 'nonfused'
    out = argv[1]
    n_int = int(argv[2]) if len(argv) > 2 else 3  # number of weak horizontal interfaces
    gc_high = float(argv[3]) if len(argv) > 3 else 1e-3  # tough (fiber) fracture energy
    gc_ratio = float(argv[4]) if len(argv) > 4 else 0.1  # gc_low / gc_high at the weak interfaces
    gc_low = gc_high * gc_ratio
    L = 0.04  # phase-field regularization length (== element ~2.4x)

    # Spatial Gc field. fused = uniform gc_high. nonfused = gc_high everywhere EXCEPT narrow horizontal bands
    # at interface heights y_k, where a Gaussian dip pulls Gc to gc_low (the weak, delaminating woven layers).
    # The crack runs horizontally along y=0.5 (mode I, vertical tension); the weak interfaces are placed
    # PARALLEL to it and OFFSET above/below 0.5 (never ON it), so the crack is deflected/delaminated ONTO
    # them (Cook-Gordon) rather than racing along a weak plane it starts on. Interfaces sit symmetric about
    # 0.5 at ±0.15, ±0.30, ...  (n_int of them). The geometry under test, vs a straight fused crack.
    _offs = [0.15 * (k + 1) for k in range((n_int + 1) // 2)]
    ys = sorted([round(0.5 - o, 4) for o in _offs] + [round(0.5 + o, 4) for o in _offs])[:n_int]
    if mode == "nonfused":
        # ~1 at each interface, 0 between
        bands = " + ".join(f"exp(-((y-{yk})/0.02)^2)" for yk in ys)
        gc_expr = f"{gc_high} - ({gc_high}-{gc_low})*min({bands}, 1)"
    elif mode == "fused":
        gc_expr = f"{gc_high}"
    else:
        sys.exit("mode must be 'fused' or 'nonfused'")

    # The deck text below is emitted verbatim (column 0 is intentional: it is file content).
    deck = f"""# WOVEN FRACTURE — {mode} (crack deflection at weak interfaces). Generated by tm6_make_woven_fracture_deck.py.
# Interfaces (y): {ys if mode=='nonfused' else 'none (uniform Gc)'}   gc_high={gc_high} gc_low={gc_low}
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 80
    ny = 80
    xmax = 1
    ymax = 1
  []
[]

[GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Modules/PhaseField/Nonconserved]
  [c]
    free_energy = F
    kappa = kappa_op
    mobility = M
  []
[]

[Physics/SolidMechanics/QuasiStatic]
  [mech]
    add_variables = true
    strain = SMALL
    additional_generate_output = 'stress_yy'
    save_in = 'resid_x resid_y'
    planar_formulation = PLANE_STRAIN
  []
[]

[ICs]
  [c_ic]
    type = FunctionIC
    function = ic
    variable = c
  []
[]

[Functions]
  [ic]                              # SMOOTH horizontal left-edge notch at y=0.5 for x<0.4 (smeared over l)
    type = ParsedFunction
    expression = 'exp(-abs(y-0.5)/{L}) * if(x<0.4, 1.0, exp(-(x-0.4)/{L}))'
  []
  [gc_func]                         # spatial fracture toughness (weak interfaces for nonfused)
    type = ParsedFunction
    expression = '{gc_expr}'
  []
[]

[AuxVariables]
  [resid_x][]
  [resid_y][]
  [bounds_dummy] order = FIRST family = LAGRANGE []
  [gc_view] order = CONSTANT family = MONOMIAL []   # so the Gc field is visible in the Exodus
[]
[AuxKernels]
  [gc_view_k] type = FunctionAux variable = gc_view function = gc_func execute_on = 'INITIAL' []
[]

[Kernels]
  [solid_x] type = PhaseFieldFractureMechanicsOffDiag variable = disp_x component = 0 c = c []
  [solid_y] type = PhaseFieldFractureMechanicsOffDiag variable = disp_y component = 1 c = c []
[]

[BCs]                               # mode I (proven-clean tm6_stageD config): pull top up, clamp bottom,
  [ypull] type = FunctionDirichletBC variable = disp_y boundary = top function = t []   # opens the y=0.5 crack
  [yfix]  type = DirichletBC variable = disp_y boundary = bottom value = 0 []
  [xfix]  type = DirichletBC variable = disp_x boundary = 'top bottom' value = 0 []
[]

[Materials]
  [gc_spatial]                      # Gc as a spatial material property from the function above
    type = GenericFunctionMaterial
    prop_names = 'gc_prop'
    prop_values = 'gc_func'
  []
  [pfconst]
    type = GenericConstantMaterial
    prop_names = 'l visco'
    prop_values = '{L} 1e-4'
  []
  [define_mobility]
    type = ParsedMaterial
    material_property_names = 'gc_prop visco'
    property_name = M
    expression = '1.0/(gc_prop * visco)'
  []
  [define_kappa]
    type = ParsedMaterial
    material_property_names = 'gc_prop l'
    property_name = kappa_op
    expression = 'gc_prop * l'
  []
  [elasticity_tensor]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 0
    euler_angle_2 = 0
    euler_angle_3 = 0
  []
  [damage_stress]
    type = ComputeLinearElasticPFFractureStress
    c = c
    E_name = 'elastic_energy'
    D_name = 'degradation'
    F_name = 'local_fracture_energy'
    decomposition_type = stress_spectral
    use_snes_vi_solver = true
  []
  [degradation]
    type = DerivativeParsedMaterial
    property_name = degradation
    coupled_variables = 'c'
    expression = '(1.0-c)^2*(1.0 - eta) + eta'
    constant_names       = 'eta'
    constant_expressions = '0.0'
    derivative_order = 2
  []
  [local_fracture_energy]
    type = DerivativeParsedMaterial
    property_name = local_fracture_energy
    coupled_variables = 'c'
    material_property_names = 'gc_prop l'
    expression = 'c^2 * gc_prop / 2 / l'
    derivative_order = 2
  []
  [fracture_driving_energy]
    type = DerivativeSumMaterial
    coupled_variables = c
    sum_materials = 'elastic_energy local_fracture_energy'
    derivative_order = 2
    property_name = F
  []
[]

[Postprocessors]
  [applied_disp] type = SideAverageValue variable = disp_y boundary = top []
  [reaction]     type = NodalSum variable = resid_y boundary = top []
  [crack_c]      type = ElementAverageValue variable = c []
[]

[Preconditioning]
  [smp] type = SMP full = true []
[]

[Bounds]
  [c_upper_bound]
    type = ConstantBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = upper
    bound_value = 1.0
  []
  [c_lower_bound]
    type = VariableOldValueBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = lower
  []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package -snes_type'
  petsc_options_value = 'lu superlu_dist vinewtonrsls'
  nl_rel_tol = 1e-7
  nl_abs_tol = 1e-9
  l_max_its = 30
  nl_max_its = 15
  dtmin = 1e-8
  end_time = 0.03
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 5e-5
    optimal_iterations = 8
    growth_factor = 1.5
    cutback_factor = 0.5
  []
[]

[Outputs]
  exodus = true
  csv = true
[]
"""
    open(out, "w").write(deck)
    print(
        f"wrote {out}: woven fracture deck, mode={mode}, interfaces={ys if mode=='nonfused' else 'none'}"
    )


if __name__ == "__main__":
    main()
