"""
tm6_make_bouligand_deck.py — generate a MOOSE phase-field-fracture deck for a Bouligand coupon,
representing its rotating-ply architecture as N vertical ply strips (subdomains), strip k
rotated by k*pitch (the coupon's real per-ply twist). A crack seeded at the left is driven
across the strips; because each ply's weak plane points a different way, the crack must
deflect at every ply boundary -> it TWISTS. Sweeping the coupon pitch (10/15/20/30 deg)
reproduces the crack-twisting experiment on the coupons' actual designs.

Full-model, robust solver (NEWTON+superlu+adaptive dt), smooth seeded crack, VI irreversibility
-- the settings validated in tm6_stageD.i.

INPUTS   <pitch_deg> <n_plies> <out.i>   (pitch per ply [deg], number of ply strips, deck path)
OUTPUTS  the MOOSE deck at <out.i> + a one-line summary on stdout. The shipped example
         abcad/fracture/decks/tm6_bouligand_d30_example.i is exactly `30 6`.
Usage: python -m abcad.fracture.tm6_make_bouligand_deck <pitch_deg> <n_plies> <out.i>
"""

from __future__ import annotations

import sys


def main(argv=None):
    """CLI entry point: write the Bouligand-coupon crack-twisting deck."""
    argv = sys.argv[1:] if argv is None else list(argv)
    # Positional CLI: print the usage (this module's docstring) for -h/--help or missing arguments
    # rather than failing with an IndexError/ValueError traceback.
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0 if argv else 2
    pitch = float(argv[0])
    N = int(argv[1])
    out = argv[2]

    W, H = 2.0, 1.0  # domain: 2 wide (crack runs +x through the plies), 1 tall
    notch = 0.5  # notch tip x; plies fill x in [notch, W]
    nx, ny = 160, 80
    strip_w = (W - notch) / N

    # --- mesh: base grid + one SubdomainBoundingBox per ply strip (block id k) ---
    mesh = [
        "[Mesh]",
        "  [gen]",
        "    type = GeneratedMeshGenerator",
        "    dim = 2",
        f"    nx = {nx}",
        f"    ny = {ny}",
        f"    xmax = {W}",
        f"    ymax = {H}",
        "  []",
    ]
    prev = "gen"
    for k in range(N):
        x0 = notch + k * strip_w
        x1 = notch + (k + 1) * strip_w
        mesh += [
            f"  [ply{k}]",
            "    type = SubdomainBoundingBoxGenerator",
            f"    block_id = {k+1}",
            f"    bottom_left = '{x0} 0 0'",
            f"    top_right = '{x1} {H} 0'",
            f"    input = {prev}",
            "  []",
        ]
        prev = f"ply{k}"
    # the notch region (x<notch) stays block 0
    mesh.append("[]")

    # --- one anisotropic elasticity material per ply strip, euler = k*pitch ---
    mats = []
    for k in range(N):
        ang = round(k * pitch, 3)
        mats += [
            f"  [elast{k}]",
            "    type = ComputeElasticityTensor",
            "    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'",
            "    fill_method = symmetric9",
            f"    euler_angle_1 = {ang}",
            f"    block = {k+1}",
            "  []",
        ]
    # notch block (0): give it an orientation too (0 deg) so the whole domain is covered
    mats += [
        "  [elast_notch]",
        "    type = ComputeElasticityTensor",
        "    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'",
        "    fill_method = symmetric9",
        "    euler_angle_1 = 0",
        "    block = 0",
        "  []",
    ]

    # The deck text below is emitted verbatim (column 0 is intentional: it is file content).
    deck = f"""# =====================================================================================
# TM-6 Stage D2 — Bouligand coupon crack twisting, pitch = {pitch} deg/ply, {N} plies.
# The coupon's rotating-ply architecture as {N} vertical ply strips (subdomains), strip k
# rotated by k*{pitch} deg. Crack seeded at the left, driven +x through the plies; each ply's
# weak plane points differently, so the crack must deflect at every ply -> it TWISTS.
# Represents bouligand_d{int(pitch)}_w.stl's ply design (not the voxel-resolved fibers).
# Generated by tm6_make_bouligand_deck.py. Robust solver from tm6_stageD.i.
# =====================================================================================
{chr(10).join(mesh)}

[GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Modules/PhaseField/Nonconserved]
  [c]
    free_energy = F
    kappa = kappa_op
    mobility = L
  []
[]

[Physics/SolidMechanics/QuasiStatic]
  [mech]
    add_variables = true
    strain = SMALL
    additional_generate_output = 'stress_yy'
    save_in = 'resid_x resid_y'
    planar_formulation = PLANE_STRAIN
  []
[]

[ICs]
  [c_ic]
    type = FunctionIC
    function = ic
    variable = c
  []
[]

[Functions]
  [ic]                              # smooth seeded notch along y=0.5 for x<{notch}
    type = ParsedFunction
    expression = 'exp(-abs(y-0.5)/0.04) * if(x<{notch}, 1.0, exp(-(x-{notch})/0.04))'
  []
[]

[AuxVariables]
  [resid_x][]
  [resid_y][]
  [bounds_dummy] order = FIRST family = LAGRANGE []
[]

[Kernels]
  [solid_x]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_x
    component = 0
    c = c
  []
  [solid_y]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_y
    component = 1
    c = c
  []
[]

[BCs]
  [ydisp]
    type = FunctionDirichletBC
    variable = disp_y
    boundary = top
    function = t
  []
  [yfix]
    type = DirichletBC
    variable = disp_y
    boundary = bottom
    value = 0
  []
  [xfix]
    type = DirichletBC
    variable = disp_x
    boundary = 'top bottom'
    value = 0
  []
[]

[Materials]
  [pfbulkmat]
    type = GenericConstantMaterial
    prop_names = 'gc_prop l visco'
    prop_values = '1e-3 0.04 1e-4'
  []
  [define_mobility]
    type = ParsedMaterial
    material_property_names = 'gc_prop visco'
    property_name = L
    expression = '1.0/(gc_prop * visco)'
  []
  [define_kappa]
    type = ParsedMaterial
    material_property_names = 'gc_prop l'
    property_name = kappa_op
    expression = 'gc_prop * l'
  []
{chr(10).join(mats)}
  [damage_stress]
    type = ComputeLinearElasticPFFractureStress
    c = c
    E_name = 'elastic_energy'
    D_name = 'degradation'
    F_name = 'local_fracture_energy'
    decomposition_type = stress_spectral
    use_snes_vi_solver = true
  []
  [degradation]
    type = DerivativeParsedMaterial
    property_name = degradation
    coupled_variables = 'c'
    expression = '(1.0-c)^2*(1.0 - eta) + eta'
    constant_names       = 'eta'
    constant_expressions = '0.0'
    derivative_order = 2
  []
  [local_fracture_energy]
    type = DerivativeParsedMaterial
    property_name = local_fracture_energy
    coupled_variables = 'c'
    material_property_names = 'gc_prop l'
    expression = 'c^2 * gc_prop / 2 / l'
    derivative_order = 2
  []
  [fracture_driving_energy]
    type = DerivativeSumMaterial
    coupled_variables = c
    sum_materials = 'elastic_energy local_fracture_energy'
    derivative_order = 2
    property_name = F
  []
[]

[Postprocessors]
  [top_disp]
    type = SideAverageValue
    variable = disp_y
    boundary = top
  []
  [reaction_y]
    type = NodalSum
    variable = resid_y
    boundary = top
  []
  [crack_c]
    type = ElementAverageValue
    variable = c
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Bounds]
  [c_upper_bound]
    type = ConstantBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = upper
    bound_value = 1.0
  []
  [c_lower_bound]
    type = VariableOldValueBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = lower
  []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package -snes_type'
  petsc_options_value = 'lu superlu_dist vinewtonrsls'
  nl_rel_tol = 1e-7
  nl_abs_tol = 1e-9
  l_max_its = 30
  nl_max_its = 15
  dtmin = 1e-8
  end_time = 0.02
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 5e-5
    optimal_iterations = 8
    growth_factor = 1.4
    cutback_factor = 0.5
  []
[]

[Outputs]
  exodus = true
  csv = true
[]
"""
    open(out, "w").write(deck)
    print(f"wrote {out}: pitch {pitch} deg, {N} plies (angles 0..{round((N-1)*pitch,1)} deg)")


if __name__ == "__main__":
    main()
