"""
tm6_make_3d_twist_deck.py — 3D phase-field crack through a rotating-plywood block.

The real Bouligand/enamel fracture signature is a TWISTED crack SURFACE: as a crack propagates
through plies whose fiber orientation rotates through the thickness, the crack must twist to
follow the rotating weak planes. 2D can only show in-plane deflection; this is the 3D version.

Block W(x) x H(y) x T(z). The thickness z is divided into N ply slabs, slab k rotated by
k*pitch (euler_angle_1). A through-thickness notch is seeded at the left (x<notch, mid-height,
spanning all z); mode-I pull drives the crack in +x. Because each z-slab's weak plane points a
different way, the crack deflects in y by a different amount at each z -> the crack SURFACE
y=f(x,z) warps/twists through the thickness. Robust solver from tm6_stageD.i, 3D.

Kept modest for the 16 GB budget (memory safety first).

INPUTS   <pitch_deg> <n_slabs> <out.i>   (pitch per ply [deg], number of ply slabs, deck path)
OUTPUTS  the MOOSE deck at <out.i> + a two-line summary on stdout. The shipped example
         abcad/fracture/decks/tm6_3d_twist_example.i is exactly `30 6`.
Usage: python -m abcad.fracture.tm6_make_3d_twist_deck <pitch_deg> <n_slabs> <out.i>
"""

from __future__ import annotations

import sys


def main(argv=None):
    """CLI entry point: write the 3D twisting-crack deck for the requested pitch and slab count."""
    argv = sys.argv[1:] if argv is None else list(argv)
    # Positional CLI: print the usage (this module's docstring) for -h/--help or missing arguments
    # rather than failing with an IndexError/ValueError traceback.
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0 if argv else 2
    pitch = float(argv[0])
    N = int(argv[1])
    out = argv[2]

    W, H, T = 1.0, 1.0, 0.5  # thickness T=0.5 holds the ply stack
    notch = 0.4  # seeded notch tip x (the crack is pre-damaged for x < notch)
    nx, ny, nz = 36, 26, 18  # ~16.8k hex; 3 elements per slab at N=6
    slab_t = T / N

    # mesh: base grid + one z-slab subdomain per ply (block id k+1)
    mesh = [
        "[Mesh]",
        "  [gen]",
        "    type = GeneratedMeshGenerator",
        "    dim = 3",
        f"    nx = {nx}",
        f"    ny = {ny}",
        f"    nz = {nz}",
        f"    xmax = {W}",
        f"    ymax = {H}",
        f"    zmax = {T}",
        "  []",
    ]
    prev = "gen"
    for k in range(N):
        z0, z1 = k * slab_t, (k + 1) * slab_t
        mesh += [
            f"  [slab{k}]",
            "    type = SubdomainBoundingBoxGenerator",
            f"    block_id = {k+1}",
            f"    bottom_left = '0 0 {z0}'",
            f"    top_right = '{W} {H} {z1}'",
            f"    input = {prev}",
            "  []",
        ]
        prev = f"slab{k}"
    mesh.append("[]")

    # one anisotropic elasticity tensor per slab, rotated by k*pitch about z
    mats = []
    for k in range(N):
        ang = round(k * pitch, 3)
        mats += [
            f"  [elast{k}]",
            "    type = ComputeElasticityTensor",
            "    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'",
            "    fill_method = symmetric9",
            f"    euler_angle_1 = {ang}",
            f"    block = {k+1}",
            "  []",
        ]

    # The deck text below is emitted verbatim (column 0 is intentional: it is file content).
    deck = f"""# =====================================================================================
# TM-6 3D twisting crack — rotating-plywood block, pitch = {pitch} deg/ply, {N} ply slabs
# through the thickness (z). Crack seeded at the left (through-thickness notch), driven +x;
# the crack SURFACE twists through z as each ply's weak plane rotates. dim = 3.
# Generated by tm6_make_3d_twist_deck.py. Memory-guard the run (16 GB budget; memory safety first).
# =====================================================================================
{chr(10).join(mesh)}

[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

[Modules/PhaseField/Nonconserved]
  [c]
    free_energy = F
    kappa = kappa_op
    mobility = L
  []
[]

[Physics/SolidMechanics/QuasiStatic]
  [mech]
    add_variables = true
    strain = SMALL
    save_in = 'resid_x resid_y resid_z'
  []
[]

[ICs]
  [c_ic]
    type = FunctionIC
    function = ic
    variable = c
  []
[]

[Functions]
  [ic]                              # through-thickness notch: x<{notch}, mid-height y=0.5, all z
    type = ParsedFunction
    expression = 'exp(-abs(y-0.5)/0.05) * if(x<{notch}, 1.0, exp(-(x-{notch})/0.05))'
  []
[]

[AuxVariables]
  [resid_x][]
  [resid_y][]
  [resid_z][]
  [bounds_dummy] order = FIRST family = LAGRANGE []
[]

[Kernels]
  [solid_x]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_x
    component = 0
    c = c
  []
  [solid_y]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_y
    component = 1
    c = c
  []
  [solid_z]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_z
    component = 2
    c = c
  []
[]

[BCs]
  [ydisp]
    type = FunctionDirichletBC
    variable = disp_y
    boundary = top
    function = '3*t'
  []
  [yfix]
    type = DirichletBC
    variable = disp_y
    boundary = bottom
    value = 0
  []
  [xfix]
    type = DirichletBC
    variable = disp_x
    boundary = 'top bottom'
    value = 0
  []
  [zfix]
    type = DirichletBC
    variable = disp_z
    boundary = back
    value = 0
  []
[]

[Materials]
  [pfbulkmat]
    type = GenericConstantMaterial
    prop_names = 'gc_prop l visco'
    prop_values = '1e-3 0.05 1e-4'
  []
  [define_mobility]
    type = ParsedMaterial
    material_property_names = 'gc_prop visco'
    property_name = L
    expression = '1.0/(gc_prop * visco)'
  []
  [define_kappa]
    type = ParsedMaterial
    material_property_names = 'gc_prop l'
    property_name = kappa_op
    expression = 'gc_prop * l'
  []
{chr(10).join(mats)}
  [damage_stress]
    type = ComputeLinearElasticPFFractureStress
    c = c
    E_name = 'elastic_energy'
    D_name = 'degradation'
    F_name = 'local_fracture_energy'
    decomposition_type = stress_spectral
    use_snes_vi_solver = true
  []
  [degradation]
    type = DerivativeParsedMaterial
    property_name = degradation
    coupled_variables = 'c'
    expression = '(1.0-c)^2*(1.0 - eta) + eta'
    constant_names       = 'eta'
    constant_expressions = '0.0'
    derivative_order = 2
  []
  [local_fracture_energy]
    type = DerivativeParsedMaterial
    property_name = local_fracture_energy
    coupled_variables = 'c'
    material_property_names = 'gc_prop l'
    expression = 'c^2 * gc_prop / 2 / l'
    derivative_order = 2
  []
  [fracture_driving_energy]
    type = DerivativeSumMaterial
    coupled_variables = c
    sum_materials = 'elastic_energy local_fracture_energy'
    derivative_order = 2
    property_name = F
  []
[]

[Postprocessors]
  [crack_c]
    type = ElementAverageValue
    variable = c
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Bounds]
  [c_upper_bound]
    type = ConstantBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = upper
    bound_value = 1.0
  []
  [c_lower_bound]
    type = VariableOldValueBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = lower
  []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package -snes_type'
  petsc_options_value = 'lu superlu_dist vinewtonrsls'
  nl_rel_tol = 1e-6
  nl_abs_tol = 1e-8
  l_max_its = 40
  nl_max_its = 15
  dtmin = 1e-8
  end_time = 0.004
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 1e-4
    optimal_iterations = 8
    growth_factor = 1.4
    cutback_factor = 0.5
  []
[]

[Outputs]
  exodus = true
[]
"""
    open(out, "w").write(deck)
    print(
        f"wrote {out}: 3D, pitch {pitch} deg, {N} z-slabs (0..{round((N-1)*pitch,1)} deg through thickness)"
    )
    print(f"  mesh {nx}x{ny}x{nz} = {nx*ny*nz} hex")


if __name__ == "__main__":
    main()
