# =====================================================================================
# TM-6 3D twisting crack — rotating-plywood block, pitch = 30.0 deg/ply, 6 ply slabs
# through the thickness (z). Crack seeded at the left (through-thickness notch), driven +x;
# the crack SURFACE twists through z as each ply's weak plane rotates. dim = 3.
# Generated by tm6_make_3d_twist_deck.py. Memory-guard the run (16 GB budget; memory safety first).
# =====================================================================================
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 36
    ny = 26
    nz = 18
    xmax = 1.0
    ymax = 1.0
    zmax = 0.5
  []
  [slab0]
    type = SubdomainBoundingBoxGenerator
    block_id = 1
    bottom_left = '0 0 0.0'
    top_right = '1.0 1.0 0.08333333333333333'
    input = gen
  []
  [slab1]
    type = SubdomainBoundingBoxGenerator
    block_id = 2
    bottom_left = '0 0 0.08333333333333333'
    top_right = '1.0 1.0 0.16666666666666666'
    input = slab0
  []
  [slab2]
    type = SubdomainBoundingBoxGenerator
    block_id = 3
    bottom_left = '0 0 0.16666666666666666'
    top_right = '1.0 1.0 0.25'
    input = slab1
  []
  [slab3]
    type = SubdomainBoundingBoxGenerator
    block_id = 4
    bottom_left = '0 0 0.25'
    top_right = '1.0 1.0 0.3333333333333333'
    input = slab2
  []
  [slab4]
    type = SubdomainBoundingBoxGenerator
    block_id = 5
    bottom_left = '0 0 0.3333333333333333'
    top_right = '1.0 1.0 0.41666666666666663'
    input = slab3
  []
  [slab5]
    type = SubdomainBoundingBoxGenerator
    block_id = 6
    bottom_left = '0 0 0.41666666666666663'
    top_right = '1.0 1.0 0.5'
    input = slab4
  []
[]

[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

[Modules/PhaseField/Nonconserved]
  [c]
    free_energy = F
    kappa = kappa_op
    mobility = L
  []
[]

[Physics/SolidMechanics/QuasiStatic]
  [mech]
    add_variables = true
    strain = SMALL
    save_in = 'resid_x resid_y resid_z'
  []
[]

[ICs]
  [c_ic]
    type = FunctionIC
    function = ic
    variable = c
  []
[]

[Functions]
  [ic]                              # through-thickness notch: x<0.4, mid-height y=0.5, all z
    type = ParsedFunction
    expression = 'exp(-abs(y-0.5)/0.05) * if(x<0.4, 1.0, exp(-(x-0.4)/0.05))'
  []
[]

[AuxVariables]
  [resid_x][]
  [resid_y][]
  [resid_z][]
  [bounds_dummy] order = FIRST family = LAGRANGE []
[]

[Kernels]
  [solid_x]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_x
    component = 0
    c = c
  []
  [solid_y]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_y
    component = 1
    c = c
  []
  [solid_z]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_z
    component = 2
    c = c
  []
[]

[BCs]
  [ydisp]
    type = FunctionDirichletBC
    variable = disp_y
    boundary = top
    function = '3*t'
  []
  [yfix]
    type = DirichletBC
    variable = disp_y
    boundary = bottom
    value = 0
  []
  [xfix]
    type = DirichletBC
    variable = disp_x
    boundary = 'top bottom'
    value = 0
  []
  [zfix]
    type = DirichletBC
    variable = disp_z
    boundary = back
    value = 0
  []
[]

[Materials]
  [pfbulkmat]
    type = GenericConstantMaterial
    prop_names = 'gc_prop l visco'
    prop_values = '1e-3 0.05 1e-4'
  []
  [define_mobility]
    type = ParsedMaterial
    material_property_names = 'gc_prop visco'
    property_name = L
    expression = '1.0/(gc_prop * visco)'
  []
  [define_kappa]
    type = ParsedMaterial
    material_property_names = 'gc_prop l'
    property_name = kappa_op
    expression = 'gc_prop * l'
  []
  [elast0]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 0.0
    block = 1
  []
  [elast1]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 30.0
    block = 2
  []
  [elast2]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 60.0
    block = 3
  []
  [elast3]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 90.0
    block = 4
  []
  [elast4]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 120.0
    block = 5
  []
  [elast5]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 150.0
    block = 6
  []
  [damage_stress]
    type = ComputeLinearElasticPFFractureStress
    c = c
    E_name = 'elastic_energy'
    D_name = 'degradation'
    F_name = 'local_fracture_energy'
    decomposition_type = stress_spectral
    use_snes_vi_solver = true
  []
  [degradation]
    type = DerivativeParsedMaterial
    property_name = degradation
    coupled_variables = 'c'
    expression = '(1.0-c)^2*(1.0 - eta) + eta'
    constant_names       = 'eta'
    constant_expressions = '0.0'
    derivative_order = 2
  []
  [local_fracture_energy]
    type = DerivativeParsedMaterial
    property_name = local_fracture_energy
    coupled_variables = 'c'
    material_property_names = 'gc_prop l'
    expression = 'c^2 * gc_prop / 2 / l'
    derivative_order = 2
  []
  [fracture_driving_energy]
    type = DerivativeSumMaterial
    coupled_variables = c
    sum_materials = 'elastic_energy local_fracture_energy'
    derivative_order = 2
    property_name = F
  []
[]

[Postprocessors]
  [crack_c]
    type = ElementAverageValue
    variable = c
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Bounds]
  [c_upper_bound]
    type = ConstantBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = upper
    bound_value = 1.0
  []
  [c_lower_bound]
    type = VariableOldValueBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = lower
  []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package -snes_type'
  petsc_options_value = 'lu superlu_dist vinewtonrsls'
  nl_rel_tol = 1e-6
  nl_abs_tol = 1e-8
  l_max_its = 40
  nl_max_its = 15
  dtmin = 1e-8
  end_time = 0.004
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 1e-4
    optimal_iterations = 8
    growth_factor = 1.4
    cutback_factor = 0.5
  []
[]

[Outputs]
  exodus = true
[]
