# =====================================================================================
# TM-6 Stage D2 — Bouligand coupon crack twisting, pitch = 30.0 deg/ply, 6 plies.
# The coupon's rotating-ply architecture as 6 vertical ply strips (subdomains), strip k
# rotated by k*30.0 deg. Crack seeded at the left, driven +x through the plies; each ply's
# weak plane points differently, so the crack must deflect at every ply -> it TWISTS.
# Represents bouligand_d30_w.stl's ply design (not the voxel-resolved fibers).
# Generated by tm6_make_bouligand_deck.py. Robust solver from tm6_stageD.i.
# =====================================================================================
[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 160
    ny = 80
    xmax = 2.0
    ymax = 1.0
  []
  [ply0]
    type = SubdomainBoundingBoxGenerator
    block_id = 1
    bottom_left = '0.5 0 0'
    top_right = '0.75 1.0 0'
    input = gen
  []
  [ply1]
    type = SubdomainBoundingBoxGenerator
    block_id = 2
    bottom_left = '0.75 0 0'
    top_right = '1.0 1.0 0'
    input = ply0
  []
  [ply2]
    type = SubdomainBoundingBoxGenerator
    block_id = 3
    bottom_left = '1.0 0 0'
    top_right = '1.25 1.0 0'
    input = ply1
  []
  [ply3]
    type = SubdomainBoundingBoxGenerator
    block_id = 4
    bottom_left = '1.25 0 0'
    top_right = '1.5 1.0 0'
    input = ply2
  []
  [ply4]
    type = SubdomainBoundingBoxGenerator
    block_id = 5
    bottom_left = '1.5 0 0'
    top_right = '1.75 1.0 0'
    input = ply3
  []
  [ply5]
    type = SubdomainBoundingBoxGenerator
    block_id = 6
    bottom_left = '1.75 0 0'
    top_right = '2.0 1.0 0'
    input = ply4
  []
[]

[GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Modules/PhaseField/Nonconserved]
  [c]
    free_energy = F
    kappa = kappa_op
    mobility = L
  []
[]

[Physics/SolidMechanics/QuasiStatic]
  [mech]
    add_variables = true
    strain = SMALL
    additional_generate_output = 'stress_yy'
    save_in = 'resid_x resid_y'
    planar_formulation = PLANE_STRAIN
  []
[]

[ICs]
  [c_ic]
    type = FunctionIC
    function = ic
    variable = c
  []
[]

[Functions]
  [ic]                              # smooth seeded notch along y=0.5 for x<0.5
    type = ParsedFunction
    expression = 'exp(-abs(y-0.5)/0.04) * if(x<0.5, 1.0, exp(-(x-0.5)/0.04))'
  []
[]

[AuxVariables]
  [resid_x][]
  [resid_y][]
  [bounds_dummy] order = FIRST family = LAGRANGE []
[]

[Kernels]
  [solid_x]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_x
    component = 0
    c = c
  []
  [solid_y]
    type = PhaseFieldFractureMechanicsOffDiag
    variable = disp_y
    component = 1
    c = c
  []
[]

[BCs]
  [ydisp]
    type = FunctionDirichletBC
    variable = disp_y
    boundary = top
    function = t
  []
  [yfix]
    type = DirichletBC
    variable = disp_y
    boundary = bottom
    value = 0
  []
  [xfix]
    type = DirichletBC
    variable = disp_x
    boundary = 'top bottom'
    value = 0
  []
[]

[Materials]
  [pfbulkmat]
    type = GenericConstantMaterial
    prop_names = 'gc_prop l visco'
    prop_values = '1e-3 0.04 1e-4'
  []
  [define_mobility]
    type = ParsedMaterial
    material_property_names = 'gc_prop visco'
    property_name = L
    expression = '1.0/(gc_prop * visco)'
  []
  [define_kappa]
    type = ParsedMaterial
    material_property_names = 'gc_prop l'
    property_name = kappa_op
    expression = 'gc_prop * l'
  []
  [elast0]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 0.0
    block = 1
  []
  [elast1]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 30.0
    block = 2
  []
  [elast2]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 60.0
    block = 3
  []
  [elast3]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 90.0
    block = 4
  []
  [elast4]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 120.0
    block = 5
  []
  [elast5]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 150.0
    block = 6
  []
  [elast_notch]
    type = ComputeElasticityTensor
    C_ijkl = '127.0 70.8 70.8 127.0 70.8 127.0 73.55 73.55 73.55'
    fill_method = symmetric9
    euler_angle_1 = 0
    block = 0
  []
  [damage_stress]
    type = ComputeLinearElasticPFFractureStress
    c = c
    E_name = 'elastic_energy'
    D_name = 'degradation'
    F_name = 'local_fracture_energy'
    decomposition_type = stress_spectral
    use_snes_vi_solver = true
  []
  [degradation]
    type = DerivativeParsedMaterial
    property_name = degradation
    coupled_variables = 'c'
    expression = '(1.0-c)^2*(1.0 - eta) + eta'
    constant_names       = 'eta'
    constant_expressions = '0.0'
    derivative_order = 2
  []
  [local_fracture_energy]
    type = DerivativeParsedMaterial
    property_name = local_fracture_energy
    coupled_variables = 'c'
    material_property_names = 'gc_prop l'
    expression = 'c^2 * gc_prop / 2 / l'
    derivative_order = 2
  []
  [fracture_driving_energy]
    type = DerivativeSumMaterial
    coupled_variables = c
    sum_materials = 'elastic_energy local_fracture_energy'
    derivative_order = 2
    property_name = F
  []
[]

[Postprocessors]
  [top_disp]
    type = SideAverageValue
    variable = disp_y
    boundary = top
  []
  [reaction_y]
    type = NodalSum
    variable = resid_y
    boundary = top
  []
  [crack_c]
    type = ElementAverageValue
    variable = c
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Bounds]
  [c_upper_bound]
    type = ConstantBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = upper
    bound_value = 1.0
  []
  [c_lower_bound]
    type = VariableOldValueBounds
    variable = bounds_dummy
    bounded_variable = c
    bound_type = lower
  []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package -snes_type'
  petsc_options_value = 'lu superlu_dist vinewtonrsls'
  nl_rel_tol = 1e-7
  nl_abs_tol = 1e-9
  l_max_its = 30
  nl_max_its = 15
  dtmin = 1e-8
  end_time = 0.02
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 5e-5
    optimal_iterations = 8
    growth_factor = 1.4
    cutback_factor = 0.5
  []
[]

[Outputs]
  exodus = true
  csv = true
[]
