# =====================================================================================
# TM-6 3D J-INTEGRAL — rotating-plywood crack, pitch 30.0 deg/ply, 5 slabs, PLA units (mm/MPa).
# J evaluated along the through-thickness crack front; each depth's plies are rotated, so J(depth)
# is the real 3D result. Generated by tm6_make_3d_jintegral_deck.py.
# =====================================================================================
[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 3
    nx = 40
    ny = 50
    nz = 10
    xmax = 20.0
    ymax = 40.0
    zmax = 10.0
  []
  [slab0]
    type = SubdomainBoundingBoxGenerator
    block_id = 1
    bottom_left = '0 0 0.0'
    top_right = '20.0 40.0 2.0'
    input = gen
  []
  [slab1]
    type = SubdomainBoundingBoxGenerator
    block_id = 2
    bottom_left = '0 0 2.0'
    top_right = '20.0 40.0 4.0'
    input = slab0
  []
  [slab2]
    type = SubdomainBoundingBoxGenerator
    block_id = 3
    bottom_left = '0 0 4.0'
    top_right = '20.0 40.0 6.0'
    input = slab1
  []
  [slab3]
    type = SubdomainBoundingBoxGenerator
    block_id = 4
    bottom_left = '0 0 6.0'
    top_right = '20.0 40.0 8.0'
    input = slab2
  []
  [slab4]
    type = SubdomainBoundingBoxGenerator
    block_id = 5
    bottom_left = '0 0 8.0'
    top_right = '20.0 40.0 10.0'
    input = slab3
  []
  [ligament]
    type = BoundingBoxNodeSetGenerator
    new_boundary = ligament
    bottom_left = '4.0 0 0'
    top_right = '20.0 0 10.0'
    input = slab4
  []
  [xpin]
    type = BoundingBoxNodeSetGenerator
    new_boundary = xpin
    bottom_left = '19.6 39.6 0'
    top_right = '20.1 40.1 10.0'
    input = ligament
  []
  [zpin]
    type = BoundingBoxNodeSetGenerator
    new_boundary = zpin
    bottom_left = '0 0 0'
    top_right = '20.0 40.0 0.01'
    input = xpin
  []
[]

[Physics/SolidMechanics/QuasiStatic]
  [all]
    add_variables = true
    strain = SMALL
    generate_output = 'stress_yy'
  []
[]

[DomainIntegral]
  integrals = JIntegral
  crack_front_points = '4.0 0.0 1.0
                        4.0 0.0 3.0
                        4.0 0.0 5.0
                        4.0 0.0 7.0
                        4.0 0.0 9.0'
  crack_direction_method = CrackDirectionVector
  crack_direction_vector = '1 0 0'
  radius_inner = '1.0 1.5 2.0'
  radius_outer = '1.5 2.0 2.5'
  incremental = false
  symmetry_plane = 1
[]

[BCs]
  [pull]
    type = NeumannBC
    variable = disp_y
    boundary = top
    value = 30.0
  []
  [ligament_y]
    type = DirichletBC
    variable = disp_y
    boundary = ligament
    value = 0
  []
  [pin_x]
    type = DirichletBC
    variable = disp_x
    boundary = xpin
    value = 0
  []
  [pin_z]
    type = DirichletBC
    variable = disp_z
    boundary = zpin
    value = 0
  []
[]

[Materials]
  [elast0]
    type = ComputeElasticityTensor
    C_ijkl = '3500 1951 1951 3500 1951 3500 2027 2027 2027'
    fill_method = symmetric9
    euler_angle_1 = 0.0
    block = 1
  []
  [elast1]
    type = ComputeElasticityTensor
    C_ijkl = '3500 1951 1951 3500 1951 3500 2027 2027 2027'
    fill_method = symmetric9
    euler_angle_1 = 30.0
    block = 2
  []
  [elast2]
    type = ComputeElasticityTensor
    C_ijkl = '3500 1951 1951 3500 1951 3500 2027 2027 2027'
    fill_method = symmetric9
    euler_angle_1 = 60.0
    block = 3
  []
  [elast3]
    type = ComputeElasticityTensor
    C_ijkl = '3500 1951 1951 3500 1951 3500 2027 2027 2027'
    fill_method = symmetric9
    euler_angle_1 = 90.0
    block = 4
  []
  [elast4]
    type = ComputeElasticityTensor
    C_ijkl = '3500 1951 1951 3500 1951 3500 2027 2027 2027'
    fill_method = symmetric9
    euler_angle_1 = 120.0
    block = 5
  []
  [stress]
    type = ComputeLinearElasticStress
  []
[]

[Executioner]
  type = Steady
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_package'
  petsc_options_value = 'lu superlu_dist'
  nl_rel_tol = 1e-8
[]

[Outputs]
  csv = true
[]
